// تحويل رموز الأخطاء من قاعدة البيانات إلى رسائل للمستخدم
const MAP: Record<string, string> = {
  AUTH_REQUIRED: 'يجب تسجيل الدخول أولاً',
  OFFICE_NAME: 'اكتب اسم المكتب',
  OFFICE_MANAGER: 'اكتب اسم المسؤول',
  OFFICE_CITY: 'اكتب المحافظة أو المدينة',
  OFFICE_LOCATION: 'حدد موقع المكتب على الخريطة',
  OFFICE_CR: 'اكتب رقم السجل التجاري',
  WORK_CC: 'اكتب سعة المحرك كما في أوراق المركبة',
  AP_KIND: 'اختر: استقبال أو وداع',
  AP_AIRPORT: 'اختر المطار',
  AP_POINT: 'حدد نقطة الانطلاق على الخريطة',
  AP_TIME: 'اختر موعداً بعد نصف ساعة على الأقل',
  AP_PAX: 'حدد عدد الأشخاص',
  AP_WAIT: 'اختر مدة الانتظار',
  AP_NOT_ENABLED: 'خدمة تكسي المطار غير مفعّلة في حسابك',
  PLATE_TAKEN: 'هذه المركبة مسجّلة على حساب آخر، تواصل مع الدعم',
  WORK_TYPE_CHANGE: 'لا يمكن تغيير نوع حساب العمل، تواصل مع الدعم',
  WORK_ROLE: 'نوع العمل غير صحيح',
  WORK_NAME: 'اكتب الاسم الكامل',
  WORK_VEHICLE: 'اختر نوع المركبة',
  WORK_CATEGORY: 'اختر فئة السيارة',
  WORK_MODEL: 'اكتب الماركة والموديل',
  WORK_YEAR: 'سنة الصنع غير صحيحة',
  WORK_COLOR: 'اكتب لون المركبة',
  WORK_PLATE: 'اكتب رقم اللوحة',
  WORK_OWNER: 'اكتب اسم مالك المركبة',
  WORK_FUEL: 'اختر نوع الوقود',
  WORK_LICENSE_DATE: 'اختر تاريخ انتهاء الرخصة',
  WORK_LICENSE: 'اكتب رقم الرخصة ومكان صدورها',
  NOT_AUTH: 'يجب تسجيل الدخول أولاً',
  TAXI_PRIORITY: 'الطلب ما زال بأولوية لسائق أعلى مستوى — حاول بعد ثوانٍ',
  LOYALTY_MIN: 'التحويل متاح من 100 نقطة فأكثر',
  LOYALTY_NOT_ENOUGH: 'نقاطك غير كافية',
  INVITE_BAD_CODE: 'رمز الدعوة غير صحيح',
  INVITE_SELF: 'لا يمكنك استخدام رمزك',
  INVITE_USED: 'تم تسجيل رمز دعوة من قبل',
  INVITE_TOO_LATE: 'رمز الدعوة للحسابات الجديدة فقط',
  RATING_EMPTY: 'اختر نجوم أو ملاحظة',
  RATING_CLOSED: 'انتهت مدة التقييم',
  RATING_BAD: 'تقييم غير صالح',
  TRIP_LOCKED: 'لا يمكن تعديل الرحلة بعد انضمام ركاب',
  RENTAL_PHOTOS: 'أضف صورة واحدة للسيارة على الأقل',
  NAME_TOO_LONG: 'الاسم طويل، الحد 40 حرفاً',
  ACCOUNT_HAS_BALANCE: 'لا يمكن حذف الحساب وفي المحفظة رصيد، استخدم رصيدك أولاً',
  ACCOUNT_ACTIVE_ORDER: 'لا يمكن حذف الحساب ولديك طلب لم ينتهِ',
  ACCOUNT_RENTED_CAR: 'لا يمكن حذف الحساب وسيارتك مؤجّرة حالياً',
  RENTAL_MISSING: 'أكمل بيانات السيارة وحدد موقعها',
  RENTAL_NO_UNITS: 'اختر مدة إيجار واحدة على الأقل',
  RENTAL_FIXED_PRICE: 'السعر الثابت مطلوب لكل مدة',
  RENTAL_NOT_AVAILABLE: 'السيارة لم تعد متاحة',
  RENTAL_BAD_PERIOD: 'المدة غير متاحة',
  RENTAL_NO_PRICE: 'اكتب السعر',
  RENTAL_ALREADY_REQUESTED: 'لديك طلب على هذه السيارة بانتظار الرد',
  TRAVEL_PROVIDER: 'سجّل بياناتك أو فعّل خدمة السفريات أولاً',
  TRAVEL_ACCOUNT: 'خدمة السفريات متاحة للسائق أو المكتب المسجّل فقط',
  TRAVEL_DESTINATION: 'اكتب الوجهة وموقع الالتقاط',
  TRAVEL_DEPARTURE: 'اختر موعد انطلاق لاحقاً',
  TRAVEL_PRICE: 'أدخل أجرة صحيحة لكل راكب',
  TRAVEL_BAGS: 'عدد الحقائب غير صحيح أو يتجاوز السعة المعلنة',
  TRAVEL_PICKUP: 'حدد موقع الالتقاط على الخريطة',
  TRAVEL_COUNT: 'تحقق من عدد الركاب والحقائب',
  TRAVEL_ACTION: 'الإجراء المطلوب غير صحيح',
  TRAVEL_LISTING_STATE: 'لا يمكن تغيير حالة هذه الرحلة',
  TRAVEL_LISTING_UNAVAILABLE: 'الرحلة لم تعد متاحة أو لا تكفي مقاعدها',
  TRAVEL_SELF_BOOK: 'لا يمكنك حجز رحلتك المنشورة',
  TRAVEL_PROVIDER_INACTIVE: 'مقدّم الخدمة غير متاح حالياً',
  TRAVEL_REQUEST_STATE: 'لا يمكن إلغاء هذا الطلب الآن',
  TRAVEL_REQUEST_CLOSED: 'أُغلق طلب السفر أو اختير له عرض آخر',
  TRAVEL_SELF_OFFER: 'لا يمكنك إرسال عرض على طلبك',
  TRAVEL_OFFER_EXISTS: 'سبق أن أرسلت عرضاً لهذا الطلب',
  TRAVEL_OFFER_NOT_FOUND: 'العرض لم يعد متاحاً',
  SHARE_INACTIVE: 'المشاركة متاحة فقط أثناء الرحلة',
  SOS_MAX_TWO: 'رقمين للأهل كحد أقصى',
  SOS_NO_EMERGENCY: 'اكتب رقم الطوارئ',
  ORDER_NOT_AVAILABLE: 'الطلب لم يعد متاحاً',
  OFFER_NOT_AVAILABLE: 'العرض لم يعد متاحاً',
  OFFER_NOT_PENDING: 'لا يمكن سحب هذا العرض',
  NO_FIXED_BUDGET: 'هذا الطلب يستقبل عروض أسعار فقط',
  VEHICLE_NOT_SUITABLE: 'مركبتك لا تناسب هذا الطلب',
  VEHICLE_MISMATCH: 'مركبتك لا تناسب هذا الطلب',
  WALLET_NEGATIVE: 'لا يمكنك استقبال الطلبات حالياً، راجع التنبيه في أعلى الشاشة',
  WALLET_BLOCKED: 'لا يمكنك استقبال الطلبات حالياً، راجع التنبيه في أعلى الشاشة',
  BAD_PRICE: 'أدخل سعراً صحيحاً',
  PRICE_OUT_OF_RANGE: 'السعر يجب أن يكون ضمن ميزانية الزبون',
  ALREADY_OFFERED: 'لديك عرض قائم على هذا الطلب',
  ITEM_FILLED: 'اكتمل هذا النوع من المركبات',
  ORDER_CLOSED: 'الطلب لم يعد متاحاً',
  OFFER_NOT_FOUND: 'العرض لم يعد متاحاً',
  HAS_ACCEPTED: 'لا يمكن الإلغاء بعد قبول عرض',
  NOT_ALLOWED: 'غير مسموح',
  FIELD_LOCKED: 'بعد الاتفاق يمكن تعديل الموعد والملاحظات فقط',
  BAD_TIME: 'اختر التاريخ والساعة',
  NO_CHANGES: 'لم يتغير شيء',
  CARD_INVALID: 'رقم البطاقة غير صحيح',
  CARD_USED: 'هذه البطاقة مستخدمة سابقاً',
  TOO_MANY_ATTEMPTS: 'محاولات كثيرة خاطئة، حاول بعد ساعة',
  ACCOUNT_SUSPENDED: 'حسابك موقوف، تواصل مع الدعم',
  ALREADY_SUSPENDED: 'الحساب موقوف مسبقاً',
  NOT_SUSPENDED: 'الحساب غير موقوف',
  BAD_SETTING: 'القيمة غير مقبولة',
  NOT_FOUND: 'غير موجود أو تمت معالجته',
  USER_NOT_FOUND: 'لا يوجد مستخدم بهذا المعرّف أو الرقم',
  SELF_TRANSFER: 'لا يمكن التحويل إلى حسابك',
  INSUFFICIENT_BALANCE: 'رصيدك لا يكفي',
  BAD_AMOUNT: 'أدخل مبلغاً صحيحاً',
  ALREADY_PAID: 'تم دفع هذا الطلب سابقاً',
  NOT_PAYABLE: 'هذا الطلب غير متاح للدفع',
  PIN_ENTER: 'أدخل الرمز السري',
  PIN_WRONG: 'الرمز السري غير صحيح',
  PIN_LOCKED: 'تم إيقاف المحفظة مؤقتاً بعد محاولات خاطئة، حاول بعد 15 دقيقة',
  PIN_REQUIRED: 'أنشئ رمزاً سرياً للمحفظة أولاً',
  PIN_FORMAT: 'الرمز السري 4 أرقام',
  PIN_WEAK: 'رمز سهل التخمين، اختر رمزاً آخر',
  DAILY_LIMIT: 'تجاوزت حد التحويل اليومي',
  NOTE_REQUIRED: 'اكتب سبب التسوية',
  PAST_TIME: 'اختر موعداً لاحقاً',
  SHARED_NOT_STARTED: 'فات موعد رحلة سابقة، اضغط «بدء الرحلة» عليها أولاً',
  SHARED_DAILY_LIMIT: 'وصلت إلى الحد: 4 رحلات مشتركة في اليوم',
  SHARED_OVERLAP: 'يتداخل موعدها مع رحلة أخرى لك',
  TRIP_FULL: 'الرحلة مكتملة',
  TAXI_SUSPENDED: 'تم إيقاف استقبال الطلبات بسبب كثرة الإلغاءات، تواصل مع الإدارة',
  REASON_REQUIRED: 'اختر السبب أو اكتبه',
  USE_CANCEL_BUTTON: 'استخدم زر إلغاء الرحلة',
  HAS_ACTIVE_TRIP: 'لديك طلب تالٍ بالفعل، أنهِ رحلتك أولاً',
  FINISH_CURRENT_FIRST: 'أنهِ الرحلة الجارية أولاً',
  BAD_STEP: 'لا يمكن تنفيذ هذه الخطوة الآن',
  TAXI_ACCEPTED: 'قبل السائق طلبك، لا يمكن الإلغاء الآن. تواصل معه',
  TAXI_PRICING_UNAVAILABLE: 'التسعير غير مفعّل لبلد حسابك حالياً',
  TAXI_PRICING_DISABLED: 'خدمة التسعير غير مفعّلة حالياً',
  BAD_TAXI_ROUTE: 'تعذر حساب المسافة أو المدة المتوقعة',
  BAD_TAXI_CATEGORY: 'فئة المركبة غير صحيحة',
  TAXI_PRICING_CONFIG_INVALID: 'إعدادات التسعير غير مكتملة، تواصل مع الإدارة',
  BAD_COUNTRY: 'رمز الدولة غير صحيح',
  BAD_EXCHANGE_RATE: 'تحقق من سعر الصرف ووحدة التقريب المدخلة',
};
export function errMsg(e: any, fallback = 'حدث خطأ، حاول مرة أخرى') {
  const raw = String(e?.message || e || '');
  const code = Object.keys(MAP).find(k => raw.includes(k));
  if (code) return MAP[code];
  if (/network|fetch/i.test(raw)) return 'تحقق من الاتصال بالإنترنت';
  return fallback;
}
