import { PGlite } from '@electric-sql/pglite';
import fs from 'fs';
const db = new PGlite();
const D='/home/user/sql-account/';
await db.exec(`
create schema auth;
create table auth.users(id uuid primary key, email text unique, phone text unique, encrypted_password text, raw_user_meta_data jsonb, banned_until timestamptz, updated_at timestamptz);
create table auth.identities(id serial, user_id uuid); create table auth.sessions(id serial, user_id uuid);
create or replace function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub', true),'')::uuid $$;
create role authenticated; create role anon;
create type user_type as enum('personal','driver');
create table profiles(id uuid primary key, email text not null default 'x', full_name text, phone text not null, avatar_url text, type user_type default 'personal', wallet_id text, country text, national_id text, vehicle_plate text, updated_at timestamptz);
create table wallets(user_id uuid primary key, balance numeric default 0);
create table rental_listings(id uuid primary key default gen_random_uuid(), provider_id uuid, brand_model text, year int, transmission text, seats int, color text, fuel text, ac boolean, photos jsonb, lat float8, lng float8, conditions text[], pricing_mode text, units text[], prices jsonb, status text default 'active', updated_at timestamptz);
create table rental_requests(id uuid primary key default gen_random_uuid(), customer_id uuid, provider_id uuid, status text, reason text, ended_at timestamptz);
create table rental_general(customer_id uuid, status text);
create table taxi_orders(user_id uuid, driver_id uuid, status text);
create table taxi_shared_trips(id uuid primary key, driver_id uuid, status text);
create table taxi_shared_requests(trip_id uuid, passenger_id uuid, status text);
create table cargo_orders(customer_id uuid, carrier_id uuid, status text);
create table event_orders(user_id uuid, status text); create table contract_orders(user_id uuid, status text);
create table sos_settings(user_id uuid); create table device_push_tokens(user_id uuid); create table taxi_driver_positions(driver_id uuid);
`);
for (const f of ['01','02','03']) await db.exec(fs.readFileSync(D+f+'.sql','utf8'));
await db.exec(`grant all on all tables in schema public to authenticated; grant usage on schema auth to authenticated; grant all on all tables in schema auth to authenticated;`);
const A='11111111-1111-1111-1111-111111111111';
await db.exec(`insert into auth.users(id,email) values('${A}','963912345678@users.mishwar.app'); insert into profiles(id,phone,wallet_id,full_name) values('${A}','+963912345678','W1','Ali');
insert into wallets values('${A}',5); insert into sos_settings values('${A}');`);
const as = async (q) => { try { await db.exec(`reset role; select set_config('request.jwt.claim.sub','${A}',false); set role authenticated;`); const r=await db.query(q); return r.rows[0]; } catch(e){ return 'ERR:'+e.message } finally { await db.exec('reset role') } };
const ok=(c,m)=>{console.log((c?'PASS ':'FAIL ')+m); if(!c) process.exitCode=1};
let r=await as(`select public.my_account() a`); ok(r.a.wallet_id==='W1'&&r.a.phone==='+963912345678','my_account');
r=await as(`select public.set_my_name('  محمد   علي ') a`); ok(r.a.full_name==='محمد علي','set name');
r=await as(`select public.set_my_name('${'x'.repeat(41)}') a`); ok(String(r).includes('NAME_TOO_LONG'),'name too long');
r=await as(`select public.set_my_name('') a`); ok(r.a.full_name===null,'clear name');
const L=(ph)=>`select public.save_rental_listing(null, '{"photos":${ph},"brand_model":"Kia","year":2020,"transmission":"auto","seats":5,"ac":true,"lat":33.5,"lng":36.3,"units":["day"],"prices":{"day":30},"pricing_mode":"fixed"}'::jsonb) a`;
r=await as(L('{}')); ok(String(r).includes('RENTAL_PHOTOS'),'0 photos rejected');
r=await as(L('{"side":"u3"}')); ok(r.a?.id,'1 photo ok');
const ph=(await db.query(`select photos from rental_listings where id='${r.a.id}'`)).rows[0].photos; ok(JSON.stringify(ph)==='{"side":"u3"}','only given photo stored');
r=await as(L('{"front":"u1","back":"u2","side":"u3"}')); ok(r.a?.id,'3 photos ok');
r=await as(`select public.delete_my_account() a`); ok(String(r).includes('ACCOUNT_HAS_BALANCE'),'balance blocks');
await db.exec(`update wallets set balance=-2`);
await db.exec(`insert into taxi_orders values('${A}',null,'accepted')`);
r=await as(`select public.delete_my_account() a`); ok(String(r).includes('ACCOUNT_ACTIVE_ORDER'),'active taxi blocks');
await db.exec(`update taxi_orders set status='completed'; update rental_listings set status='rented' where photos ? 'front'`);
r=await as(`select public.delete_my_account() a`); ok(String(r).includes('ACCOUNT_RENTED_CAR'),'rented car blocks');
await db.exec(`update rental_listings set status='active'; insert into rental_requests(customer_id,provider_id,status) values(gen_random_uuid(),'${A}','pending')`);
r=await as(`select public.delete_my_account() a`); ok(r.a?.ok===true,'negative balance allowed, deleted');
const p=(await db.query(`select * from profiles`)).rows[0], u=(await db.query(`select * from auth.users`)).rows[0];
ok(p.phone===null&&p.deleted_at&&p.wallet_id==='W1','profile anonymised');
ok(u.email.startsWith('deleted.')&&u.banned_until&&u.encrypted_password==='','auth disabled');
ok((await db.query(`select count(*)::int c from rental_listings where status<>'deleted'`)).rows[0].c===0,'listings hidden');
ok((await db.query(`select status from rental_requests`)).rows[0].status==='rejected','pending requests rejected');
ok((await db.query(`select count(*)::int c from sos_settings`)).rows[0].c===0,'sos wiped');
